import React from 'react'

function ParentPage() {
  return (
    <div className='w-[300px] p-12'>
        <h1 className='text-4xl'>ParentPage</h1>
<p>hello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisj hello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisj hello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisjhello how are yojbs djsjs dsd fgg rdd djs djs js lorem djsos dj dolor sit ameg lorem dolor sit ameh dkdh eisj</p>
    </div>
  )
}

export default ParentPage